### ISSUE TITLE
;p from bot dont work

### ISSUE THREAD

**Issue by Brammy2904** [Mehul343/PokeGrinder#1]
My bot is typing ;p but there isnt spawning any mon
and if i paste my user auth token than it isnt working.

**Comment by Mehul343** [comment]
Please make sure that Pokemeow has permission to send messages in the channel you are grinding in. And please make sure that you are using your own account token and not an official bot token. If you don't know how to get a toke you can refer to this video https://youtu.be/YEgFvgg7ZPI.

**Comment by Brammy2904** [comment]
I managed to get my own account to send something but it only sends ;p and then it doesn't work anymore
