### ISSUE TITLE
Automatic battle bot

### ISSUE THREAD

**Issue by Brammy2904** [Mehul343/PokeGrinder#10]
It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.

**Comment by Mehul343** [comment]
> It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.

A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.

**Comment by Brammy2904** [comment]
> > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> 
> A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.

I would really love to have this feature. Is there any way I can get these anyway?

**Comment by Mehul343** [comment]
> > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > 
> > 
> > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> 
> I would really love to have this feature. Is there any way I can get these anyway?

You can make one yourself. But I can't share mine.

**Comment by Brammy2904** [comment]
> > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > 
> > > 
> > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > 
> > 
> > I would really love to have this feature. Is there any way I can get these anyway?
> 
> You can make one yourself. But I can't share mine.

Is there any way I can convince you lol

**Comment by Mehul343** [comment]
There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple. 

> > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > 
> > > 
> > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > 
> > 
> > I would really love to have this feature. Is there any way I can get these anyway?
> 
> You can make one yourself. But I can't share mine.

There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.

**Comment by Mehul343** [comment]
> > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > 
> > > > 
> > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > 
> > > 
> > > I would really love to have this feature. Is there any way I can get these anyway?
> > 
> > 
> > You can make one yourself. But I can't share mine.
> 
> Is there any way I can convince you lol

No

**Comment by Brammy2904** [comment]
> There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> 
> > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > 
> > > > 
> > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > 
> > > 
> > > I would really love to have this feature. Is there any way I can get these anyway?
> > 
> > 
> > You can make one yourself. But I can't share mine.
> 
> There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.

I'm only good at programming in java and javascript

**Comment by Brammy2904** [comment]
> There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> 
> > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > 
> > > > 
> > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > 
> > > 
> > > I would really love to have this feature. Is there any way I can get these anyway?
> > 
> > 
> > You can make one yourself. But I can't share mine.
> 
> There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.

is there any forum or server where i can ask some questions about this?

**Comment by Mehul343** [comment]
> > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > 
> > > > > 
> > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > 
> > > > 
> > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > 
> > > 
> > > You can make one yourself. But I can't share mine.
> > 
> > 
> > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.
> 
> I'm only good at programming in java and javascript

You can make discord bots in java

**Comment by Brammy2904** [comment]
> > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > 
> > > > > > 
> > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > 
> > > > > 
> > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > 
> > > > 
> > > > You can make one yourself. But I can't share mine.
> > > 
> > > 
> > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.
> > 
> > 
> > I'm only good at programming in java and javascript
> 
> You can make discord bots in java

really?!!!

**Comment by Mehul343** [comment]
> > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > 
> > > > > 
> > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > 
> > > > 
> > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > 
> > > 
> > > You can make one yourself. But I can't share mine.
> > 
> > 
> > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's 

> > > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > > 
> > > > > > > 
> > > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > > 
> > > > > > 
> > > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > > 
> > > > > 
> > > > > You can make one yourself. But I can't share mine.
> > > > 
> > > > 
> > > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.
> > > 
> > > 
> > > I'm only good at programming in java and javascript
> > 
> > 
> > You can make discord bots in java
> 
> really?!!!

Yes

**Comment by Brammy2904** [comment]
> > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > 
> > > > > > 
> > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > 
> > > > > 
> > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > 
> > > > 
> > > > You can make one yourself. But I can't share mine.
> > > 
> > > 
> > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's
> 
> > > > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > > > 
> > > > > > > 
> > > > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > > > 
> > > > > > 
> > > > > > You can make one yourself. But I can't share mine.
> > > > > 
> > > > > 
> > > > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.
> > > > 
> > > > 
> > > > I'm only good at programming in java and javascript
> > > 
> > > 
> > > You can make discord bots in java
> > 
> > 
> > really?!!!
> 
> Yes

is there any way to contact you instead via issues

**Comment by Mehul343** [comment]
> > > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > > 
> > > > > > > 
> > > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > > 
> > > > > > 
> > > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > > 
> > > > > 
> > > > > You can make one yourself. But I can't share mine.
> > > > 
> > > > 
> > > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's
> > 
> > 
> > > > > > There are Python APIs by which you can get the type of enemy pokemon. Then calculate weaknesses according to their types then just send moves according to that. It's that simple.
> > > > > > > > > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I would really love to have this feature. Is there any way I can get these anyway?
> > > > > > > 
> > > > > > > 
> > > > > > > You can make one yourself. But I can't share mine.
> > > > > > 
> > > > > > 
> > > > > > There are Python APIs which can give you the type of a pokemon. Use that type to calculate weaknesses then send the moves according to that. It's that simple.
> > > > > 
> > > > > 
> > > > > I'm only good at programming in java and javascript
> > > > 
> > > > 
> > > > You can make discord bots in java
> > > 
> > > 
> > > really?!!!
> > 
> > 
> > Yes
> 
> is there any way to contact you instead via issues

Gyomei#0777

**Comment by Brammy2904** [comment]
> Gyomei#777

from where is this?

**Comment by Brammy2904** [comment]
> Gyomei#0777

oh discord

**Comment by meonkgemas** [comment]
> > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> 
> A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.

Since this one will mess up battle tower, is it possible for you to make a feature for auto battling npcs with only one move?

**Comment by Brammy2904** [comment]
> > > It might be cool to create a function that you give the specific move number and that the bot starts batting every 60 seconds and uses that specific move.
> > 
> > 
> > A specific move number wouldn't make a good battle bot. I have made a battle bot myself which can use moves according to the enemy weaknesses. But I won't be uploading it to github as it would just mess up the Battle Tower.
> 
> Since this one will mess up battle tower, is it possible for you to make a feature for auto battling npcs with only one move?

that's what I meant actually
