### ISSUE TITLE
Sometimes dont autobuy ball

### ISSUE THREAD

**Issue by thorvak** [Mehul343/PokeGrinder#15]
Hello bot working fine during few times and after stop autobuy ball https://i.imgur.com/la1jx27.png I have to buy 1 ball manually and after it's working fine

**Comment by Mehul343** [comment]
> Hello bot working fine during few times and after stop autobuy ball https://i.imgur.com/la1jx27.png I have to buy 1 ball manually and after it's working fine

Does it have a particuler pattern of when it happens?

**Comment by thorvak** [comment]
> > Hello bot working fine during few times and after stop autobuy ball https://i.imgur.com/la1jx27.png I have to buy 1 ball manually and after it's working fine
> 
> Does it have a particuler pattern of when it happens?

No it's weird, it's not a important issue its happen rarely

**Comment by thorvak** [comment]
> > Hello bot working fine during few times and after stop autobuy ball https://i.imgur.com/la1jx27.png I have to buy 1 ball manually and after it's working fine
> 
> Does it have a particuler pattern of when it happens?

It happens here https://i.imgur.com/slnDQK1.png https://i.imgur.com/GUmwPIb.png

**Comment by Mehul343** [comment]
I found the issue. Whenever the bot has to send the ball 2 times because pokemeow doesn't register it, when that happens if it has 0 balls it will never purchase more.

**Comment by Mehul343** [comment]
This is fixed in the newest version of the bot. Thank You.
