### ISSUE TITLE
I can't run the bot since the playsound is missing I think? 

### ISSUE THREAD

**Issue by didizhou25** [Mehul343/PokeGrinder#18]

**Comment by didizhou25** [comment]
![image](https://user-images.githubusercontent.com/19870943/147382665-a8bfd061-0d92-41fb-b7e4-92ce9a3a8e69.png)

**Comment by thorvak** [comment]
> ![image](https://user-images.githubusercontent.com/19870943/147382665-a8bfd061-0d92-41fb-b7e4-92ce9a3a8e69.png)

I got same issue, uninstall all version python and install last version, dont forget select add path when you install

**Comment by didizhou25** [comment]
I tried that already

**Comment by thorvak** [comment]
you did python -m pip install -r requirements.txt

**Comment by didizhou25** [comment]
Yes I have.

**Comment by thorvak** [comment]
Try https://github.com/Mehul343/PokeGrinder/issues/2#issuecomment-997942109
