### ISSUE TITLE
Fishing exception

### ISSUE THREAD

**Issue by Brammy2904** [Mehul343/PokeGrinder#19]
i get this error every time the bot want to fish (i think)
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready
    await fishchannel.send(";f")
AttributeError: 'NoneType' object has no attribute 'send'
Task exception was never retrieved
future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")>
Traceback (most recent call last):
  File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log
    time_elapsed=current_time - start_time
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'

**Comment by Mehul343** [comment]
> i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'

Did you put channel id for fishing?

**Comment by Mehul343** [comment]
Fishing and hunting both are working for me. So the problem must be with your config.

**Comment by thorvak** [comment]
> i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'


Try create a new server only for fishing and set your new channel id in ur config.json

**Comment by Brammy2904** [comment]
> > i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
> 
> Try create a new server only for fishing and set your new channel id in ur config.json

i did that

**Comment by Brammy2904** [comment]
> > i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
> 
> Try create a new server only for fishing and set your new channel id in ur config.json

i think the problem is in the packages, so i try to reinstall all the requirements

**Comment by Brammy2904** [comment]
> > i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
> 
> Try create a new server only for fishing and set your new channel id in ur config.json

nvm i paste the serverid instead of the channelid

**Comment by Mehul343** [comment]
> > > i get this error every time the bot want to fish (i think) Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\verbe\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 89, in on_ready await fishchannel.send(";f") AttributeError: 'NoneType' object has no attribute 'send' Task exception was never retrieved future: <Task finished name='Task-62' coro=<log() done, defined at C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py:65> exception=TypeError("unsupported operand type(s) for -: 'datetime.datetime' and 'int'")> Traceback (most recent call last): File "C:\Users\verbe\Downloads\PokeGrinder-main2\PokeGrinder-main\main.py", line 67, in log time_elapsed=current_time - start_time TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'int'
> > 
> > 
> > Try create a new server only for fishing and set your new channel id in ur config.json
> 
> nvm i paste the serverid instead of the channelid

Turn on developer mode in settings it makes it easier to get ids.
