### ISSUE TITLE
The Bot does not catch Pokemon

### ISSUE THREAD

**Issue by Lykanthropie87** [Mehul343/PokeGrinder#22]
Hi i have a problem with the bot. After x hours i finally i made the bot tu run. But after the ;p command, the bot doesnt catch the pokemon. he only writes "pb" in the chat. Can someone help me with what i'm doing wrong?

**Comment by Lykanthropie87** [comment]
> 

hi thanks for the fast answer. yeah thats what i did. I changed the tokens and ids to my. And i added the DC token.

**Comment by Lykanthropie87** [comment]
After a few hours I found out thats the pip list was outdated. So i try to find a way for updating this things. But if i start the command to do, i get the following massage : "Defaulting to user installation because normal site-packages is not writeable" 
Or thats my aoihttp its outdated. If i try the aoihttp to update, i get the same massge. With the command "pip list" I wanted to test whether the updates were installed. But nothing changes. Sry for my english and im fully new on this. 

After the bot init. he wirtes the ";p" command in the channel. After the Pokemon drops the bot only wirtes "pb" in the channel. But nothing happens, And then he repeat this.

**Comment by Brammy2904** [comment]
> After a few hours I found out thats the pip list was outdated. So i try to find a way for updating this things. But if i start the command to do, i get the following massage : "Defaulting to user installation because normal site-packages is not writeable" Or thats my aoihttp its outdated. If i try the aoihttp to update, i get the same massge. With the command "pip list" I wanted to test whether the updates were installed. But nothing changes. Sry for my english and im fully new on this.
> 
> After the bot init. he wirtes the ";p" command in the channel. After the Pokemon drops the bot only wirtes "pb" in the channel. But nothing happens, And then he repeat this.

try to delete all the packages writen in the requirements.txt (manual) and after that reinstall them (manual)

**Comment by GenieRoach** [comment]
have you toggled your profile catch to text instead of buttons?

**Comment by GenieRoach** [comment]
the bot is writing pb in chat (using your name I assume) because it's trying to throw a pokeball at the mon.
If you have not changed the toggle catch (;profile toggle catch) and have it so you have to select the button ball then the bot won't work. 
Use the command listed above if that sounds correct. 
Good luck.

**Comment by GenieRoach** [comment]
> After a few hours I found out thats the pip list was outdated. So i try to find a way for updating this things. But if i start the command to do, i get the following massage : "Defaulting to user installation because normal site-packages is not writeable" Or thats my aoihttp its outdated. If i try the aoihttp to update, i get the same massge. With the command "pip list" I wanted to test whether the updates were installed. But nothing changes. Sry for my english and im fully new on this.
> 
> After the bot init. he wirtes the ";p" command in the channel. After the Pokemon drops the bot only wirtes "pb" in the channel. But nothing happens, And then he repeat this.

the bot is writing pb in chat (using your name I assume) because it's trying to throw a pokeball at the mon.
If you have not changed the toggle catch (;profile toggle catch) and have it so you have to select the button ball then the bot won't work.
Use the command listed above if that sounds correct.
Good luck.

**Comment by Lykanthropie87** [comment]
OH MY GOD. ty!!! All. The "toggle chatch" was the problem..... Ty guys! And sry :,D
