### ISSUE TITLE
errno2 No such file was found "config.json"

### ISSUE THREAD

**Issue by vulolsad** [Mehul343/PokeGrinder#23]
**Describe the bug**
module not found even type "python -m pip install -r requirements.txt" in cmd

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/90034261/148371212-75573d58-0e5c-4f93-8d3b-6567dd9e99b0.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vulolsad** [comment]
![image](https://user-images.githubusercontent.com/90034261/148371363-e57e54bb-dc66-44cb-ac7d-38998dc1ec34.png)

**Comment by Devil-commits** [comment]
I think it is an issue on your end because it works pretty fine for me, and it should work fine for others.
Try this: pip install pyfiglet

**Comment by vulolsad** [comment]
![image](https://user-images.githubusercontent.com/90034261/148487148-6cce5e46-fe7e-42e0-bb99-263dcf97a4bc.png)
it said that its alr installed, but the bug still not fixed

**Comment by Devil-commits** [comment]
It's probably an issue on your end, it works pretty fine for me.

**Comment by Devil-commits** [comment]
This may be of your help.
https://www.reddit.com/r/learnpython/comments/jyknyk/python_no_module_named_pyfiglet/

**Comment by vulolsad** [comment]
none work sad

**Comment by GenieRoach** [comment]
try using python -m pip uninstall -r requirements.txt
then use python -m pip install -r requirements.txt

Author advised me that and got it working well.

**Comment by Devil-commits** [comment]
Try doing that^^
also, is the package download path the same as the path python is in?

**Comment by vulolsad** [comment]
> try using python -m pip uninstall -r requirements.txt then use python -m pip install -r requirements.txt
> 
> Author advised me that and got it working well.

hi thx for help me, but it doesn't work :(

**Comment by vulolsad** [comment]
> Try doing that^^ also, is the package download path the same as the path python is in?

yes, it is

**Comment by Devil-commits** [comment]
> > Try doing that^^ also, is the package download path the same as the path python is in?
> 
> yes, it is

u sure?the warning line says something different tho...The script pyfiglet exe is installed in <path> which is not on PATH.

**Comment by vulolsad** [comment]
> > > Try doing that^^ also, is the package download path the same as the path python is in?
> > 
> > 
> > yes, it is
> 
> u sure?the warning line says something different tho...The script pyfiglet exe is installed in _path_ which is not on PATH.

oh sorry, um, so what i can do for now?

**Comment by Devil-commits** [comment]
add it to path i guess?

**Comment by vulolsad** [comment]
> add it to path i guess?

um how?

**Comment by vulolsad** [comment]
> add it to path i guess?

ok nvm i fixed it. But i got another error, the auto farm got up, i do saw the logo, but right after that its automatic close it self
