### ISSUE TITLE
Add Super Rare Expensive Rarity

### ISSUE THREAD

**Issue by thorvak** [Mehul343/PokeGrinder#26]
Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png
Thanks for all

**Comment by Brammy2904** [comment]
> Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png Thanks for all

I was able to code this. I can give you the code if you want

**Comment by thorvak** [comment]
> > Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png Thanks for all
> 
> I was able to code this. I can give you the code if you want

With pleasure, thanks.

**Comment by Brammy2904** [comment]
> > > Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png Thanks for all
> > 
> > 
> > I was able to code this. I can give you the code if you want
> 
> With pleasure, thanks.

I was also able to code that with every single pokemon such as a shiny and a legendary you get a plays sound.

**Comment by Brammy2904** [comment]
> > > Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png Thanks for all
> > 
> > 
> > I was able to code this. I can give you the code if you want
> 
> With pleasure, thanks.

Replace the code in hunt.py with this code.
------------------------------------------------
from lib.parser import conf
from playsound import playsound
notification = r'lib/assets/notification.mp3'
rarities = ['Common', 'Uncommon', 'Alolan', 'Super-Rare', 'Rare', 'Full-odds', 'Shiny', 'Legendary']

cheap_legies=["Articuno", "Zapdos", "Mew*", "Jirachi", 
              "Moltres", "Raikou", "Entei", 
              "Suicune", "Ho-oh", "Regirock", 
              "Regice", "Registeel", "Latias", 
              "Latios", "Deoxys", "Uxie", 
              "Mesprit", "Azelf", "Heatran", 
              "Regigigas", "Cresselia", "Cobalion", 
              "Terrakion", "Virizion", "Tornadus", 
              "Thundurus", "Landorus", "Xerneas", 
              "Yveltal", "Celebi", "Zygarde"]
Event_sr=["Darmanitan-Zen", "Furfrou-Star"]
def hunt(footer, description):
    for rarity in rarities:
        if rarity in footer:
            if rarity == "Super-Rare":
                if any(poke in description for poke in Event_sr):
                    ball = conf.rarities.Legendary
                    playsound(notification)
            else:
                ball = conf.rarities[str(rarity)]
                
            if rarity == "Legendary":
                if any(poke in description for poke in cheap_legies):
                    ball = conf.rarities.Cheap_legendary
                    playsound(notification)
                else:
                    ball = conf.rarities.Legendary
                    playsound(notification)
            elif rarity == "Shiny":
                    ball = conf.rarities[str(rarity)]
                    playsound(notification)
                                
            elif rarity == "Full-odds":
                ball = conf.rarities.FUll_odds
                playsound(notification)
            
            else:
                ball = conf.rarities[str(rarity)]
            
            break

    return ball

**Comment by Brammy2904** [comment]
> > > Hello can you add Super Rare Expensive Rarity, because Super Rare Event have high price so I want throw mb and not only ub like here https://i.imgur.com/Ey3SnFc.png Thanks for all
> > 
> > 
> > I was able to code this. I can give you the code if you want
> 
> With pleasure, thanks.

Do you understand?

**Comment by thorvak** [comment]
You sure about Super-Rare and not Super Rare ?

**Comment by Brammy2904** [comment]
> You sure about Super-Rare and not Super Rare ?

Well noticed I forgot to adjust it after I tested it

**Comment by thorvak** [comment]
Thanks, with your script you already captured  Darmanitan-Zen, Furfrou-Star with mb ?

**Comment by Brammy2904** [comment]
> Thanks, with your script you already captured Darmanitan-Zen, Furfrou-Star with mb ?

yes

**Comment by thorvak** [comment]
Nice

**Comment by thorvak** [comment]
No work for me https://i.imgur.com/yJpidcm.png

**Comment by thorvak** [comment]
No work for me https://i.imgur.com/yJpidcm.png

https://pastebin.com/FPhJFFVC

**Comment by thorvak** [comment]
No work for me https://i.imgur.com/yJpidcm.png
https://pastebin.com/CtP8nbaX

**Comment by thorvak** [comment]
Work fine with https://pastebin.com/KG0ufUdS
