### ISSUE TITLE
Need some help setting this up.

### ISSUE THREAD

**Issue by Toanl31** [Mehul343/PokeGrinder#28]
I've done the setup and so far the following:

1. Downloaded the repo
2. Installed Python
3. Ran the requirements syntax
4. Updated the config.json

I'm not sure if perhaps my 'general' section has a syntax error? I know the token field is correct as I've checked it twice using developer mode on chrome to get the token from the application section. 

Below is the 'general' section and the error message:

{   
    "general": {
        "token": "123example I put this in quotes",
        "hunting": "enable",
        "channelid": "numbers in quotes",
        "fishing": "disable",
        "fishchannelid": "",
        "anticaptcha_token": "",
        "captcha_solver": "disable",
        "captcha_notifier": "disable",
        "eggs": "enable",
        "autobuy": "disable"
    },

Error image: [https://i.imgur.com/SQuww0q.png](url)

**Comment by thorvak** [comment]
You sure your token is good ? Give me your discord I can help you

**Comment by Devil-commits** [comment]
Hey i don't think you should put '' or "" in places with Numbers like channelid, fishchannelid or userid

**Comment by Toanl31** [comment]
I receive this when I remove the quotes:

`PS C:\Users\Desktop\PokeMeow\PokeGrinder-main> python main.py
System: Windows
 ____       _         ____      _           _
|  _ \ ___ | | _____ / ___|_ __(_)_ __   __| | ___ _ __
| |_) / _ \| |/ / _ \ |  _| '__| | '_ \ / _` |/ _ \ '__|
|  __/ (_) |   <  __/ |_| | |  | | | | | (_| |  __/ |
|_|   \___/|_|\_\___|\____|_|  |_|_| |_|\__,_|\___|_|


Importing Modules...
Traceback (most recent call last):
  File "C:\Users\Desktop\PokeMeow\PokeGrinder-main\main.py", line 17, in <module>
    from lib.hunt import hunt
  File "C:\Users\Desktop\PokeMeow\PokeGrinder-main\lib\hunt.py", line 1, in <module>
    from lib.parser import conf
  File "C:\Users\Desktop\PokeMeow\PokeGrinder-main\lib\parser.py", line 30, in <module>
    conf = Configuration.load_json('config.json')
  File "C:\Users\Desktop\PokeMeow\PokeGrinder-main\lib\parser.py", line 27, in load_json
    result = Configuration.__load__(json.loads(f.read()))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 18 (char 39)
PS C:\Users\Desktop\PokeMeow\PokeGrinder-main>

**Comment by Devil-commits** [comment]
copy the config.json file from this repo, and paste it in your config..then make changes by adding token, channel id, etc.
