### ISSUE TITLE
AntiCaptcha Setup

### ISSUE THREAD

**Issue by Toanl31** [Mehul343/PokeGrinder#30]
Hello,

I've setup the Anti-Captcha token and topped up an account. I also enabled the captcha_solver in the config.json and entered the anticaptcha_token using these parameters:

https://i.imgur.com/kgpKyW4.png

Once a captcha has been found, it says 'Unable to solve captcha'! 

config.json setup like this and works when I 'empty' out:
anticaptcha_token to ""
captcha_solver to 'disable'.

"general": {
        "token": "123",
        "userid": 123,
        "hunting": "enable",
        "channelid": 123,
        "fishing": "enable",
        "fishchannelid": 123,
        "anticaptcha_token": "123",
        "captcha_solver": "enable",
        "captcha_notifier": "enable",
        "eggs": "enable",
        "autobuy": "disable"

**Comment by thorvak** [comment]
You have balance in your Anti-Captcha account ?

**Comment by Toanl31** [comment]
Yeah, $10

**Comment by thorvak** [comment]
Try https://i.imgur.com/tI7AMD7.png

**Comment by Toanl31** [comment]
Yep, already set. 

https://i.imgur.com/v5GmWIQ.png

**Comment by Toanl31** [comment]
Oh, it was actually working the entire time? It finally didn't automatically 'fail'. It took maybe 20 seconds now to try to solve.

Anyway to make it more accurate?

https://i.imgur.com/UE1eK1q.png

**Comment by Toanl31** [comment]
So what I'm noticing is...every 1 in 5 Captchas it will attempt to solve.

The other 4 will 'auto fail' within 1 second it won't attempt to solve, it'll just go immediately to the notification sound.
