### ISSUE TITLE
The bot spams ;f

### ISSUE THREAD

**Issue by GlaceonPKMN** [Mehul343/PokeGrinder#32]
The bot spams ;f and Made the fish ran away,is there a way to avoid this?

**Comment by Devil-commits** [comment]
hm so i have faced similar issues, but assumed that it's because i kept the hunting channel and fishing channel same, instead of keeping them different, i started fishing manually. I guess you should try keeping both the channels different and report the output here.

**Comment by GlaceonPKMN** [comment]
Ill try the different server one and ill see how it goes,thanks everyone!
