### ISSUE TITLE
Usage of this code in another project

### ISSUE THREAD

**Issue by Devil-commits** [Mehul343/PokeGrinder#4]
Am I allowed to use the code of this project in one of the other projects I am working on?

**Comment by Mehul343** [comment]
> Am I allowed to use the code of this project in one of the other projects I am working on?

What is your project about?

**Comment by Devil-commits** [comment]
> > Am I allowed to use the code of this project in one of the other projects I am working on?
> 
> What is your project about?

Same thing lol...but different bot

**Comment by Mehul343** [comment]
> > > Am I allowed to use the code of this project in one of the other projects I am working on?
> > 
> > 
> > What is your project about?
> 
> Same thing lol...but different bot

Yes you can use my code but the LICENSE file in my repo must be in your repo to as a copyright.

**Comment by Devil-commits** [comment]
Okay...so the same file i can put?

**Comment by Mehul343** [comment]
> Okay...so the same file i can put?

Yes

**Comment by Devil-commits** [comment]
k thanks so i'll close this issue
