### ISSUE TITLE
How to complete step #3?

### ISSUE THREAD

**Issue by Hamzaaab511** [Mehul343/PokeGrinder#43]
Greetings

I'm new to this whole area and subject can someone please guide through step number 3? I installed python but can't seem to figure out how to open the repo or what a repo is exactly.

Thank you

**Comment by vulolsad** [comment]
ok did you download the bot? if yes unzip it then reply me

**Comment by Hamzaaab511** [comment]
> ok did you download the bot? if yes unzip it then reply me

I downloaded it and unzipped it. I also downloaded the latest version of Python.

**Comment by bruhsus123** [comment]
ok now open the file you got after unzipped and you will see the path on the top of file like in this pi
![no](https://user-images.githubusercontent.com/90034261/153995265-48760f5f-3d6b-4313-8d7e-7ccc68216c16.png)
c

**Comment by bruhsus123** [comment]
clear the path and type cmd and press enter

**Comment by bruhsus123** [comment]
in the command type "python -m pip install -r requirements.txt" and enter

**Comment by bruhsus123** [comment]
reply me if you done all this step

**Comment by Hamzaaab511** [comment]
done and it is working now. Thank you
