### ISSUE TITLE
Encountering a KeyError when captcha comes:

### ISSUE THREAD

**Issue by Devil-commits** [Mehul343/PokeGrinder#7]
When the time of captcha solving comes, a key error is raise for solution and text in captcha.py file. Please look into it.

**Comment by Mehul343** [comment]
> When the time of captcha solving comes, a key error is raise for solution and text in captcha.py file. Please look into it.

Yeah I think that is because of anticaptcha not returning an answer. I will still look into it tomorrow as it is like 11pm here.

**Comment by Devil-commits** [comment]
I just removed ['solution'] and ['text'] from captcha.py and it started working smoothly
