### ISSUE TITLE
Notifier bug

### ISSUE THREAD

**Issue by Pufflie** [Mehul343/PokeGrinder#8]
The bot sometimes shows couldn't solve captcha and plays the notifier sound but it actually solved the captcha, and auto resumes catching. 

The Pokemeow bot replies `, thank you, you may continue hunting!` but the farm bot responses `Couldn't solve captcha!`, with sound notifier but resumed catching and worked normally again.

**Comment by Devil-commits** [comment]
How did you even get the captcha working?For me it raises a keyerror

**Comment by Pufflie** [comment]
> How did you even get the captcha working?For me it raises a keyerror

Sometimes it happens to have this https://imgur.com/SQywxhl , but after keying the captcha manually it will auto resume. https://imgur.com/3Lt6BS0

**Comment by Pufflie** [comment]
> > How did you even get the captcha working?For me it raises a keyerror
> 
> Sometimes it happens to have this https://imgur.com/SQywxhl , but after keying the captcha manually it will auto resume. https://imgur.com/3Lt6BS0.
But the mentioned bug still happens from time to time where a false failed to solve happens

**Comment by Devil-commits** [comment]
> > How did you even get the captcha working?For me it raises a keyerror
> 
> Sometimes it happens to have this https://imgur.com/SQywxhl , but after keying the captcha manually it will auto resume. https://imgur.com/3Lt6BS0

Same happens to me , but the captcha is never solved by the bot...Mehul343 told that he would look in this issue today.....

**Comment by Mehul343** [comment]
> > > How did you even get the captcha working?For me it raises a keyerror
> > 
> > 
> > Sometimes it happens to have this https://imgur.com/SQywxhl , but after keying the captcha manually it will auto resume. https://imgur.com/3Lt6BS0
> 
> Same happens to me , but the captcha is never solved by the bot...Mehul343 told that he would look in this issue today.....

I have updates the bot. Please try again.
