### ISSUE TITLE
NoneType Object has no attribute

### ISSUE THREAD

**Issue by adsiao** [Mehul343/PokeGrinder#9]
**Describe the bug**

hello, i have this error on it.

 i also did try to to edit at Line 48 that add my channelid instead of conf.general.channelid) it will go to ;p and stuck over there

Initialising, this may take some time depending on your hardware.
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Lau Hou\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Lau Hou\Desktop\PokeGrinder-main\main.py", line 50, in on_ready
    await channel.send(";p")
AttributeError: 'NoneType' object has no attribute 'send'

**Comment by Mehul343** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> hello, i have this error on it.
> 
> i also did try to to edit at Line 48 that add my channelid instead of conf.general.channelid) it will go to ;p and stuck over there
> 
> Initialising, this may take some time depending on your hardware. Ignoring exception in on_ready Traceback (most recent call last): File "C:\Users\Lau Hou\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 301, in _run_event await coro(*args, **kwargs) File "C:\Users\Lau Hou\Desktop\PokeGrinder-main\main.py", line 50, in on_ready await channel.send(";p") AttributeError: 'NoneType' object has no attribute 'send'

Please make sure that you put the correct channelid in config.json.

**Comment by adsiao** [comment]
yup i did put the correct channelid in config.
